kind: Deployment
apiVersion: apps/v1
metadata:
   name: test-app
spec:
   replicas: 2
   selector: 
    matchLabels:
     app: test-app
   template:
      metadata:
        labels:
          app: test-app
      spec:
       containers:
        - name: test-app
          image: louiepython2024/test-pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80