kind: Service                             
apiVersion: v1
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: test-app                  
  type: LoadBalancer 