kind: Deployment
apiVersion: apps/v1
metadata:
   name: test-app
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: test-app
   template:
      metadata:
        labels:
          app: test-app
      spec:
       containers:
        - name: test-app
          image: vikashashoke/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80